### Creating Array

In [1]:
import numpy as np

In [2]:
# array
arr = np.array([1, 2, 3])
arr.shape, arr

((3,), array([1, 2, 3]))

In [3]:
a1 = np.array([5, 10])
a2 = np.array([[3, 2], 
               [5, 6]])
a3 = np.array([[[1, 2], 
                [4, 5]], 
              [[5, 6], 
               [8, 0]]])
a1.shape, a2.shape, a3.shape

((2,), (2, 2), (2, 2, 2))

In [4]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [5]:
a3.dtype

dtype('int32')

In [6]:
a1.size, a3.size

(2, 8)

In [7]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(a2)

In [10]:
df

0  1
0  3  2
1  5  6

### Different Ways to Create Array

In [11]:
np.ones(shape=(3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.zeros(shape=(4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.arange(start=3, stop=20, step=2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
np.random.randint(2, 22, size=(3, 4))

array([[ 6, 18, 20, 21],
       [11, 10, 15, 17],
       [15,  4, 13, 20]])

In [15]:
np.random.random(size=(5, 3))

array([[0.07608299, 0.42121889, 0.62751767],
       [0.99295244, 0.66455986, 0.98027782],
       [0.12024801, 0.48662223, 0.91999324],
       [0.98601181, 0.71223523, 0.02738618],
       [0.11964728, 0.8547826 , 0.96761739]])

In [16]:
np.random.rand(3, 3, 3)

array([[[0.31015508, 0.62015911, 0.68183409],
        [0.05789331, 0.035151  , 0.86696461],
        [0.94438283, 0.55766177, 0.37984637]],

       [[0.5945608 , 0.06367106, 0.59522823],
        [0.58076128, 0.21917737, 0.56738535],
        [0.49784588, 0.38337352, 0.5349866 ]],

       [[0.03797691, 0.36311868, 0.0605837 ],
        [0.18608426, 0.58744404, 0.02046736],
        [0.99014382, 0.16886399, 0.28765878]]])

In [17]:
## Changing Random Seed
np.random.seed(42)

In [18]:
np.random.randn(3, 4)

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

### viewing arrays and matrices

In [19]:
# unique elements in array
np.unique(np.array([[1, 2, 3], [2, 1, 5], [5, 6, 3]]))

array([1, 2, 3, 5, 6])

In [20]:
a3

array([[[1, 2],
        [4, 5]],

       [[5, 6],
        [8, 0]]])

In [21]:
a3[1]

array([[5, 6],
       [8, 0]])

In [22]:
a3[1][0]

array([5, 6])

In [23]:
# looping through all indices
a3[:, :, 1]

array([[2, 5],
       [6, 0]])

In [24]:
a3[:, :, 0]

array([[1, 4],
       [5, 8]])

In [25]:
a4 = np.random.randint(0, 99, size=(3, 4, 5, 2))

In [26]:
a4[:2, :, :, 0]

array([[[75, 21, 48, 58, 91],
        [79, 61, 46, 50, 63],
        [50, 20, 38,  3, 59],
        [ 8, 52, 83, 59, 43]],

       [[46, 77, 35,  3,  5],
        [ 3, 92, 17, 43, 73],
        [13, 47, 71, 86, 39],
        [79, 52, 25, 59, 28]]])

### Manipulation of Arrays

#### Arithmetic

In [27]:
a = np.array([2, 3, 4])
b = np.array([1, 4, 5])
a, b

(array([2, 3, 4]), array([1, 4, 5]))

In [28]:
a + b

array([3, 7, 9])

In [29]:
a - b

array([ 1, -1, -1])

In [30]:
a * b

array([ 2, 12, 20])

In [31]:
a / b

array([2.  , 0.75, 0.8 ])

In [32]:
a % b

array([0, 3, 4])

In [33]:
a ** b

array([   2,   81, 1024])

In [34]:
a // b

array([2, 0, 0])

In [35]:
a ** 5

array([  32,  243, 1024], dtype=int32)

In [36]:
np.square(a)

array([ 4,  9, 16])

In [37]:
np.add(a, 4)

array([6, 7, 8])

In [38]:
np.log(b)

array([0.        , 1.38629436, 1.60943791])

#### Aggregation

In [39]:
# numpy methods should be used on ndarray datatypes and use python methods on python datatypes
# even though they give same result but on long run it wouldn't be good
np.sum(a), sum(a)

(9, 9)

In [40]:
big_array = np.random.random(size=(3000000))

In [41]:
big_array.size

3000000

In [42]:
%timeit sum(big_array)


646 ms ± 116 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
%timeit np.sum(big_array)

8.91 ms ± 391 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [44]:
np.mean(big_array)

0.4999780533002282

In [45]:
np.max(big_array)

0.9999993822414859

In [46]:
np.std(big_array)

0.28861846842051186

In [47]:
np.var(big_array)

0.08330062031340202

#### reshape or Transpose

In [48]:
a = np.random.randint(0, 10, size=(2, 3))
b = np.random.randint(0, 10, size=(2, 3, 3))

In [49]:
a, b

(array([[8, 8, 9],
        [0, 5, 9]]),
 array([[[3, 5, 1],
         [9, 4, 3],
         [2, 8, 6]],
 
        [[3, 1, 6],
         [1, 8, 7],
         [6, 1, 1]]]))

In [50]:
# this would work because of different shape
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [51]:
np.reshape(a, (2, 3, 1)) * b

array([[[24, 40,  8],
        [72, 32, 24],
        [18, 72, 54]],

       [[ 0,  0,  0],
        [ 5, 40, 35],
        [54,  9,  9]]])

In [52]:
c = np.transpose(b)
c

array([[[3, 3],
        [9, 1],
        [2, 6]],

       [[5, 1],
        [4, 8],
        [8, 1]],

       [[1, 6],
        [3, 7],
        [6, 1]]])

In [53]:
c.shape, b.shape

((3, 3, 2), (2, 3, 3))

In [54]:
# or simply use Property of array to see transpose
a.T

array([[8, 0],
       [8, 5],
       [9, 9]])

### Dot Product

In [56]:
np.random.seed(42)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [58]:
# this is element-wise multiplication of vectors
mat1 * mat2

array([[24,  3, 49],
       [20,  6, 36],
       [ 0, 54, 35],
       [32,  0, 63],
       [14, 12, 15]])

In [60]:
# Dot Product
np.dot(mat1, mat2.T)

array([[ 76,  61,  62, 111,  51],
       [ 85,  62,  99, 113,  71],
       [ 63,  44,  89,  79,  61],
       [ 68,  51,  62,  95,  47],
       [ 65,  57,  43, 101,  41]])

### Comparison Operator

In [62]:
a1 = np.array([[1, 2], 
               [4, 3]])
a2 = np.array([[3, 1], 
               [5, 2]])

In [63]:
a1 > a2

array([[False,  True],
       [False,  True]])

In [64]:
a1 <= a2

array([[ True, False],
       [ True, False]])

In [65]:
a1 > 2

array([[False, False],
       [ True,  True]])

In [66]:
a2 <= 3

array([[ True,  True],
       [False,  True]])

In [67]:
a1 == a2

array([[False, False],
       [False, False]])

### Sorting Array

In [68]:
ran_arr = np.random.randint(10, size=(3, 5))
ran_arr

array([[8, 2, 4, 2, 6],
       [4, 8, 6, 1, 3],
       [8, 1, 9, 8, 9]])

In [69]:
np.sort(ran_arr)

array([[2, 2, 4, 6, 8],
       [1, 3, 4, 6, 8],
       [1, 8, 8, 9, 9]])

In [71]:
# return sorted indices array
np.argsort(ran_arr)

array([[1, 3, 2, 4, 0],
       [3, 4, 0, 2, 1],
       [1, 0, 3, 2, 4]], dtype=int64)

In [78]:
# return indices of min no. in each column
np.argmin(ran_arr, axis=0)

array([1, 2, 0, 1, 1], dtype=int64)

In [79]:
# return indices of max number in each row
np.argmax(ran_arr, axis=1)

array([0, 1, 2], dtype=int64)

## Convert Image into Numpy Array

<img src="sample_image.jpg">

In [81]:
from matplotlib import image as mpimg

In [83]:
img = mpimg.imread("sample_image.jpg")

In [84]:
img.shape

(480, 771, 3)

In [88]:
img[:2]

array([[[10, 10, 22],
        [11, 11, 23],
        [14, 12, 25],
        ...,
        [ 9, 12, 29],
        [ 9, 12, 29],
        [ 9, 12, 29]],

       [[ 9,  9, 21],
        [11, 11, 23],
        [15, 13, 26],
        ...,
        [10, 13, 30],
        [10, 13, 30],
        [10, 13, 30]]], dtype=uint8)

In [89]:
img.ndim

3