In [22]:
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [99]:
housing = pd.read_csv("housing.csv\\housing.csv")

In [100]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [101]:
housing = housing.dropna()

In [102]:
op = housing["ocean_proximity"]
op_dict = {i:v for v, i in enumerate(op.unique())}
op_arr = np.array([op_dict[i] for i in op])
housing["ocean_proximity"] = op_arr

C:\Users\SG704\AppData\Local\Temp\ipykernel_4664\131289279.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  housing["ocean_proximity"] = op_arr


In [103]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

       ocean_proximity  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
...                ...  
20635                2  
20636                2  
20637                2  
20638                2  
20639                2  

[20433 rows x 10 columns]

In [28]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [132]:
labels = housing["median_house_value"].to_numpy()
data = housing[["latitude", "longitude", "housing_median_age", "total_rooms", "total_bedrooms", "population", "households", "median_income", "ocean_proximity"]]

In [109]:
data

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0         37.88    -122.23                41.0        880.0           129.0   
1         37.86    -122.22                21.0       7099.0          1106.0   
2         37.85    -122.24                52.0       1467.0           190.0   
3         37.85    -122.25                52.0       1274.0           235.0   
4         37.85    -122.25                52.0       1627.0           280.0   
...         ...        ...                 ...          ...             ...   
20635     39.48    -121.09                25.0       1665.0           374.0   
20636     39.49    -121.21                18.0        697.0           150.0   
20637     39.43    -121.22                17.0       2254.0           485.0   
20638     39.43    -121.32                18.0       1860.0           409.0   
20639     39.37    -121.24                16.0       2785.0           616.0   

       population  households  median_income  ocean_proximity  
0           322.0       126.0         8.3252                0  
1          2401.0      1138.0         8.3014                0  
2           496.0       177.0         7.2574                0  
3           558.0       219.0         5.6431                0  
4           565.0       259.0         3.8462                0  
...           ...         ...            ...              ...  
20635       845.0       330.0         1.5603                2  
20636       356.0       114.0         2.5568                2  
20637      1007.0       433.0         1.7000                2  
20638       741.0       349.0         1.8672                2  
20639      1387.0       530.0         2.3886                2  

[20433 rows x 9 columns]

In [133]:
labels

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.])

In [134]:
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

In [135]:
data_scaled.shape

(20433, 9)

In [136]:
BATCH_SIZE = 128
batched_data = np.empty((0, 32, 9))
batched_labels = np.empty((0, 32))
i=0
for i in range(0, len(data)//32):
    batched_data = np.append(batched_data, data_scaled[i:i+32].reshape(1, 32, 9), axis=0)
    batched_labels = np.append(batched_labels, labels[i:i+32].reshape(1, 32), axis=0)
    i += 32

In [139]:
batched_label_scaled = batched_labels / labels.max()

In [141]:
batched_label_scaled, batched_label_scaled.shape

(array([[0.90519819, 0.71699857, 0.70419859, ..., 0.26399947, 0.24459951,
         0.23039954],
        [0.71699857, 0.70419859, 0.68259863, ..., 0.24459951, 0.23039954,
         0.22079956],
        [0.70419859, 0.68259863, 0.68439863, ..., 0.23039954, 0.22079956,
         0.20979958],
        ...,
        [0.39659921, 0.31479937, 0.52939894, ..., 0.39459921, 0.38519923,
         0.38439923],
        [0.31479937, 0.52939894, 0.43679913, ..., 0.38519923, 0.38439923,
         0.38919922],
        [0.52939894, 0.43679913, 0.47019906, ..., 0.38439923, 0.38919922,
         0.38699923]]),
 (638, 32))

In [152]:
638 * 0.9

574.2

In [153]:
model = keras.Sequential([
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(128, kernel_regularizer="L1"), 
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(32), 
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(8), 
    keras.layers.Dense(1)
])
model.compile(optimizer=keras.optimizers.Adam(learning_rate=5e-4), loss=keras.losses.mse)

In [154]:
model.fit(batched_data[:510], batched_label_scaled[:510], epochs=250, 
         validation_data=(batched_data[510:574], batched_label_scaled[510:574]), 
         callbacks=[keras.callbacks.EarlyStopping(monitor="val_loss", patience=10)])

Epoch 1/250
16/16 [==============================] - 1s 23ms/step - loss: 4.1311 - val_loss: 1.4592
Epoch 2/250
16/16 [==============================] - 0s 15ms/step - loss: 3.0363 - val_loss: 1.3483
Epoch 3/250
16/16 [==============================] - 0s 14ms/step - loss: 2.6841 - val_loss: 1.2760
Epoch 4/250
16/16 [==============================] - 0s 13ms/step - loss: 2.4397 - val_loss: 1.2155
Epoch 5/250
16/16 [==============================] - 0s 12ms/step - loss: 2.1758 - val_loss: 1.1647
Epoch 6/250
16/16 [==============================] - 0s 12ms/step - loss: 2.0396 - val_loss: 1.1221
Epoch 7/250
16/16 [==============================] - 0s 12ms/step - loss: 1.8244 - val_loss: 1.0832
Epoch 8/250
16/16 [==============================] - 0s 12ms/step - loss: 1.7257 - val_loss: 1.0459
Epoch 9/250
16/16 [==============================] - 0s 12ms/step - loss: 1.6202 - val_loss: 1.0112
Epoch 10/250
16/16 [==============================] - 0s 12ms/step - loss: 1.5055 - val_loss: 0.9774

16/16 [==============================] - 0s 10ms/step - loss: 0.0618 - val_loss: 0.0492
Epoch 83/250
16/16 [==============================] - 0s 10ms/step - loss: 0.0610 - val_loss: 0.0472
Epoch 84/250
16/16 [==============================] - 0s 11ms/step - loss: 0.0583 - val_loss: 0.0457
Epoch 85/250
16/16 [==============================] - 0s 12ms/step - loss: 0.0563 - val_loss: 0.0444
Epoch 86/250
16/16 [==============================] - 0s 12ms/step - loss: 0.0549 - val_loss: 0.0427
Epoch 87/250
16/16 [==============================] - 0s 13ms/step - loss: 0.0532 - val_loss: 0.0428
Epoch 88/250
16/16 [==============================] - 0s 12ms/step - loss: 0.0520 - val_loss: 0.0408
Epoch 89/250
16/16 [==============================] - 0s 12ms/step - loss: 0.0509 - val_loss: 0.0413
Epoch 90/250
16/16 [==============================] - 0s 12ms/step - loss: 0.0498 - val_loss: 0.0403
Epoch 91/250
16/16 [==============================] - 0s 12ms/step - loss: 0.0485 - val_loss: 0.0391
Epo

In [155]:
model.evaluate(batched_data[574:], batched_label_scaled[574:])

2/2 [==============================] - 0s 6ms/step - loss: 0.0141


0.014128157868981361

In [156]:
preds = model.predict(batched_data[574:])

2/2 [==============================] - 0s 2ms/step


In [157]:
preds[:1], preds.shape

(array([[[0.39062512],
         [0.38695818],
         [0.3904007 ],
         [0.40529722],
         [0.4406368 ],
         [0.4036941 ],
         [0.39280123],
         [0.39152926],
         [0.41145033],
         [0.40701663],
         [0.3619815 ],
         [0.3452075 ],
         [0.3801543 ],
         [0.35221398],
         [0.44778407],
         [0.39308417],
         [0.3758434 ],
         [0.39888054],
         [0.38785416],
         [0.34291473],
         [0.36126536],
         [0.35686088],
         [0.33612648],
         [0.34342074],
         [0.35047072],
         [0.30050224],
         [0.32686278],
         [0.3678515 ],
         [0.30854088],
         [0.31929857],
         [0.2766323 ],
         [0.32201457]]], dtype=float32),
 (64, 32, 1))

In [158]:
preds = preds.reshape(64, 32) * labels.max()

In [159]:
preds[:1], preds.shape

(array([[195312.95, 193479.48, 195200.75, 202649.02, 220318.84, 201847.45,
         196401.  , 195765.02, 205725.58, 203508.72, 180991.12, 172604.1 ,
         190077.53, 176107.34, 223892.48, 196542.48, 187922.08, 199440.67,
         193927.47, 171457.7 , 180633.05, 178430.8 , 168063.58, 171710.72,
         175235.72, 150251.42, 163431.72, 183926.11, 154270.75, 159649.61,
         138316.44, 161007.61]], dtype=float32),
 (64, 32))

In [160]:
acc_value = batched_labels[574:]

In [161]:
acc_value[:1], acc_value.shape

(array([[248600., 254900., 241500., 295200., 340400., 274700., 238600.,
         266400., 330200., 206800., 209200., 195800., 253500., 241800.,
         252500., 263900., 227000., 220900., 259300., 232500., 231600.,
         209400., 223200., 209900., 208200., 203800., 195700., 190500.,
         181000., 184900., 190800., 242200.]]),
 (64, 32))

In [162]:
np.average(acc_value - preds)

31115.752182006836